version: '3.8'
services:
  security_service:
    container_name: security
    image: postgres:alpine
    environment:
      POSTGRES_USER: SECURITY
      POSTGRES_PASSWORD: SECURITY
      POSTGRES_DB: User
    ports:
      - '5437:5432'
    volumes:
      - securityData:/var/lib/postgresql/data
  product_service:
    container_name: product
    image: postgres
    environment:
      POSTGRES_USER: ROOT
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: EvoProduct
    ports:
     - '5433:5432'
    volumes:
     - productDataEvo:/var/lib/postgresql/data


  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      - REDIS_PASSWORD=ecommerce-redis-p@ss
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6380:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'


volumes:
  securityData: {}
  redis_data: {}
  productDataEvo: {}