spring:
  application:
    name: EcommerceBackend
  data:
    redis:
      #host: redis
      #port: 6380
      host: localhost
      port: 6380
      password: ecommerce-redis-p@ss
      timeout: 60000
      client-type: lettuce

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


  datasource:
    first:
#      url: jdbc:postgresql://security_service:5432/User
      url: jdbc:postgresql://localhost:5437/User
      username: SECURITY
      password: SECURITY
    second:
#      url: jdbc:postgresql://product_service:5432/EvoProduct
      url: jdbc:postgresql://localhost:5433/EvoProduct

      username: ROOT
      password: 1234
    third:
#      url: jdbc:postgresql://order_service:5432/Order
      url: jdbc:postgresql://localhost:5434/Order

      username: ORDER
      password: 12345
    fourth:
#      url: jdbc:postgresql://admin_service:5432/Admin
      url: jdbc:postgresql://localhost:5435/Admin
      username: ADMIN
      password: 12345
  jpa:
    show-sql: true
    first:
     hibernate:
      ddl-auto: update
    second:
      hibernate:
        ddl-auto: update



  mail:
    host: smtp.gmail.com
    port: 587
    username: memmedlisedat033@gmail.com
    password: ghfs orqj yyyf envz
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true


      security:
        oauth2:
          client:
            registration:
              google:
                client-id: 523070151170-f80npg62nl1rapmi86m2f2c2efgthibi.apps.googleusercontent.com

security:
  key: "jvdIc8VZQrh6T17RAywe6e/3u7wQ/WEXIUuLD1FWYo01yQcjjmjOBfwY/KeHu5cBaNMeJI0pZIMOwNCQuVnMvQ=="
refresh-token:
  expiration: 2592000000

access-token:
  expiration: 600000

verification-code:
  expiration: 300000

activation-token:
  expiration: 86400000

cloudinary:
  cloud:
    name: dxwnhu7af
    api-key: 842273197433114
    api-secret: Pk4pPw0keRWoNMLMeaNPnWJlFQQ

server:
  port: 8081